### ISSUE TITLE
Add option to disable responsive layout

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-north#1]
Right now, there's no way for a user to disable the responsive layout if they don't want to use it.

**Comment by gregpriday** [comment]
The easiest way to do this would be to add a setting, which would disable the [viewport header](https://github.com/siteorigin/siteorigin-north/blob/develop/header.php#L14).

It's generally considered good practice to have as little code in the header as possible. So it would be better to have this all handled in a function in `functions.php`, that's hooked to the `wp_head` action.

This setting should also an argument to the `siteorigin-panels` add [theme support call](https://github.com/siteorigin/siteorigin-north/blob/develop/functions.php#L98). Something like `'responsive' => siteorigin_setting( 'layout_responsive' ),`

**Comment by adiraomj** [comment]
I'm running into one problem, when sticky menu enabled the fixed position style is applied to #masthead. So in smaller screens with responsive layout disabled, the #masthead is fixed to the left and does not move with horizontal scroll. Was wondering how to solve this.

**Comment by adiraomj** [comment]
How about this, if I change [this line](https://github.com/siteorigin/siteorigin-north/blob/develop/js/north.js#L239) to `'left': 0 - self.pageXOffset+'px',` it solves the problem. 

Is this the best way to go about it ?

**Comment by gregpriday** [comment]
I thought there might be a few more challenges to this issue that I hadn't thought about.

The only issue with changing that line to `'left': 0 - self.pageXOffset+'px',`, is that might not handle the case of having something set in Customize > Theme Settings > Header > Text Above. This slightly offsets the top of the menu and is the reason the sentinel positioning was important.

If that solution works in all cases, including having something in *Text Above* though, then it's a good solution. If you submit a PR, I'll do some testing myself.

**Comment by adiraomj** [comment]
I have submitted a PR.

I did not find any problems with the `#topbar` with changing the line of js. 

Please check the PR and let me know if everything works as expected or if I overlooked anything.

**Comment by gregpriday** [comment]
This was resolved by https://github.com/siteorigin/siteorigin-north/pull/11
