### ISSUE TITLE
Remove resize_logo setting

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/siteorigin-north#102]
We have the [resize_logo](https://github.com/siteorigin/siteorigin-north/blob/develop/inc/settings.php#L198) setting which is the same as the [sticky_scale](https://github.com/siteorigin/siteorigin-north/blob/develop/inc/settings.php#L193) setting above it. 

Moreover `resize_logo` is not used anywhere in our code.

**Comment by gregpriday** [comment]
Nicely spotted. Nothing wrong with removing it then.
