### ISSUE TITLE
Search icon animation is missing

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#109]
We've lost the search icon animation in branch: develop. Can we get that back? Thanks :)

**Comment by adiraomj** [comment]
@Misplon @gregpriday should we apply the animation to the [close search link](https://github.com/siteorigin/siteorigin-north/blob/develop/header.php#L93) or to our [svg icon](https://github.com/siteorigin/siteorigin-north/blob/develop/header.php#L95). Both will affect the user uploaded icons in different ways. What do you think?
