### ISSUE TITLE
Comment out SO Premium attribution setting in Customizer

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#111]
Comment out the attribution setting in the Customizer until SO Premium is ready.

@gregpriday to attend as he's keen to add additional page settings functionality to tie into your new CPT builder plugin.

**Comment by Misplon** [comment]
Expand this issue to all other premium links in the Customizer like AJAX Comments.

**Comment by gregpriday** [comment]
Resolved in https://github.com/siteorigin/siteorigin-north/commit/a30e6bc39cee246c525b3a761c59156acde790ac
