### ISSUE TITLE
Consider making the sidebar width a measurement setting

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#112]
The sidebar width setting could be tightened up a bit. Right now if a user doesn't insert the percentage symbol the setting doesn't work. The user can also add a minus sign and break the layout, `-10%` for example. My idea would be to change the setting label to the following:

**Sidebar Width (%)**

And then change the field to a measurement field, ideally with a min and max. We could also use a description line to explain percentage, min and max information.

**Comment by Misplon** [comment]
The same question/improvement also needs to be applied to the following settings:

**Header:**
Border Width
Padding
Bottom Margin

**Footer:**
Border Width
Top Padding
Side Padding
Top Margin

The way we're handling Responsive > Menu Breakpoint is cool, no unit indication is required in the field.

**Comment by adiraomj** [comment]
For the sidebar width a user can also choose to input a width using px or em (for example: 400px). It will work especially well when the user has the responsive layout disabled.

**Comment by Misplon** [comment]
@adiraomj Definitely, I can see that use case. I'm not sure how common it will be though. My thought with this enhancement is to make this and similar settings quite bulletproof. For a fixed width sidebar we could either help a user out with a Custom CSS snippet OR we could have one field for the value and another for the unit, with a drop-down menu with the available units.

**Comment by Misplon** [comment]
@adiraomj Greg's idea is to make the measurement fields the same as they are in Page Builder with a value field and a unit drop-down menu. This should add the flexibility you're after and the robustness I'm keen for. Next update though.

**Comment by Misplon** [comment]
@gregpriday Is the settings framework ready for this yet? If so I'll assign to Adi.

**Comment by gregpriday** [comment]
Not yet, will take a quick look now to see if it's easy enough, else this can wait until after SiteOrigin Premium launch.

**Comment by gregpriday** [comment]
@Misplon - got this working. Can you double check it?

**Comment by Misplon** [comment]
@gregpriday Fantastic, thanks, it's working nicely and everything looks much cleaner like this.

Does the setting have the ability to set one unit of measurement? Would it be neater if we changed the Menu Breakpoint setting to a measurement but only offered up px in the unit drop-down menu?

**Comment by gregpriday** [comment]
That isn't currently an option, but for that particular case, we'd just stick to a text field. For consistency though, it would be a good idea that sort of functionality to the measurement field.

**Comment by Misplon** [comment]
Thanks for the feedback. I'll log the request, you can tackle when all the prio 1 and 2 tasks are complete, if you keen.
