### ISSUE TITLE
Header padding setting isn't live loading

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#113]
The Header > Padding setting doesn't appear to be live loading. The bottom margin setting below it does though.

**Comment by Misplon** [comment]
Same challenge for Footer > Top Padding.

**Comment by gregpriday** [comment]
The masthead has to do with how we're handling masthead scaling on scroll. Footer padding settings are working for me though. Can you double check that?

**Comment by gregpriday** [comment]
The solution for masthead is to just remove real-time updating from that setting.

**Comment by Misplon** [comment]
Awesome, thanks for explaining.
