### ISSUE TITLE
Add ability to set color / background for the current page item in the navigation

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#122]
There should be a way to set the color or background, for the current page in the navigation. It seems odd not to be able to set this.

**Comment by Misplon** [comment]
We considered this when adding the current menu item styling recently. We're trying to keep the settings a minimal as possible. The current menu indication is currently set to the Dark Text Color. How many users have asked to change this particular color?

**Comment by AlexGStapleton** [comment]
Half a dozen at the most. Might not be worth it in hindsight.

**Comment by Misplon** [comment]
@gregpriday You keen to add a current menu item color and hover setting for North?
