### ISSUE TITLE
Improve mobile version of the shopping cart.

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-north#125]
There are a few things we could do to improve the mobile version of the cart. The first would be showing a smaller thumbnail image. The current one takes up too much space and can cause some text wrapping with longer titles.

The second issue is the delete button. At the moment, this starts overlapping the cart totals area.

<img width="344" alt="screen shot 2016-05-20 at 7 28 09 pm" src="https://cloud.githubusercontent.com/assets/1126859/15436231/18e70bf0-1ec1-11e6-8e4d-4f31b91f4787.png">

**Comment by Misplon** [comment]
@adiraomj Looks like we might have some button spacing challenges on mobile. The below is emulated for the iPhone 5. Can you suggest a better layout here?

![cart_ _siteorigin_css](https://cloud.githubusercontent.com/assets/789159/15477817/1d828178-2117-11e6-979f-bd82ff7748f5.png)

**Comment by adiraomj** [comment]
What we could do is make the coupon code field and all the following buttons full width for small screens. Sound good?

**Comment by Misplon** [comment]
Sounds good :)
