### ISSUE TITLE
Scrolling issue on iOS

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-north#126]
When scrolling on an iPhone, the menu disappears when scrolling. This can be seen on the North Demo.

http://demo.siteorigin.com/north/

Here is a video of the issue in action:

[scrolling-issue.mp4.zip](https://github.com/siteorigin/siteorigin-north/files/275157/scrolling-issue.mp4.zip)

**Comment by gregpriday** [comment]
Taking a look at this.

**Comment by gregpriday** [comment]
For now, we're going to solve this by disabling the sticky menu on mobile. If I look at the code, this was actually the original intention. There are a few other issues that we'd need to solve before having a proper mobile sticky menu.

**Comment by Misplon** [comment]
@gregpriday There is quite a lot of support to get the sticky header back onto mobile. Thanks man.
