### ISSUE TITLE
Odd formatting of menu search on iOS

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-north#127]
This is most likely due to the default styling that iOS applies to search input elements. This can probably be overcome with some extra CSS. Ideally we want the search on iOS to look the same as it does on desktop.

Here's how it looks on iOS:

<img width="378" alt="screen shot 2016-05-20 at 7 46 26 pm" src="https://cloud.githubusercontent.com/assets/1126859/15436732/afe664ae-1ec3-11e6-9fd0-c6d3ad771578.png">

And here's how it looks on desktop:

<img width="412" alt="screen shot 2016-05-20 at 7 48 17 pm" src="https://cloud.githubusercontent.com/assets/1126859/15436770/d3149e5a-1ec3-11e6-9e75-011a7798776e.png">

**Comment by Misplon** [comment]
@adiraomj did #130 resolve the problem during testing? The issue remains for me when testing locally on iOS Chrome.

**Comment by adiraomj** [comment]
I tested it with Xcode's iPhone simulator. The issue seemed to be solved there. I'll have another look.

**Comment by Misplon** [comment]
Thanks @adiraomj can you check develop branch in Xcode, I'm looking now and the problem seems to persist.

**Comment by gregpriday** [comment]
I'll look into this now.

**Comment by gregpriday** [comment]
It's working for me now. Just needed to hard refresh Simulator.
