### ISSUE TITLE
Cart page: when the sidebar is present the Update Cart button needs bottom spacing

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#131]
Let's take a look at the button alignment when the default page layout (sidebar) is used on the cart page.

![cart_ _siteorigin](https://cloud.githubusercontent.com/assets/789159/15477668/2b43e064-2116-11e6-9b09-37805a598648.png)

**Comment by gregpriday** [comment]
@Misplon - I think I fixed this with this commit - https://github.com/siteorigin/siteorigin-north/commit/024e22901cbbe2d2e2b0b2a61e86c83b55f8ea16

Can you double check if it's all working well for you?

**Comment by Misplon** [comment]
@gregpriday Perfect
