### ISSUE TITLE
Duplicate menu

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#134]
[Reported here](https://siteorigin.com/thread/siteorigin-north-theme-menu-does-not-close-windows10-chrome/)

Have two sub-menus in the main nav. Click one of the links to get focus but ensure it doesn't navigate. Then hover over another sub menu. It should show two menus.

This can be replicated in the [demo](https://demo.siteorigin.com/north/).

Reference image:
![](https://i.imgur.com/GSS8TVO.png)

**Comment by AlexGStapleton** [comment]
I've done some more testing and this can apparently happen in any browser. Including, apparently without effort, on iPad when the mobile menu isn't visible. This might be a p1.

**Comment by Misplon** [comment]
@adiraomj Hopefully, I'm not experiencing a caching issue. I can still recreate this problem from the develop branch.

![img_1420](https://cloud.githubusercontent.com/assets/789159/15634987/9fd3bed4-25d2-11e6-977f-0ff73bc02581.PNG)

Are you able to recreate this issue?

**Comment by adiraomj** [comment]
This issue is happening because we show a dropdown when a link is in focus (needed for [full-accessibility](https://make.wordpress.org/themes/handbook/review/accessibility/required/#keyboard-navigation)). I'll see if we can limit this interaction to keyboard input only.

**Comment by adiraomj** [comment]
@Misplon @gregpriday do you think tampering with this will affect full accessibility? 

> Passes: Dropdown navigation menus are hidden using position: absolute; and brought into view on :hover and :focus, and are navigable using the tab key

From what I understand, the link has `:focus` state. And this is what is supposed to happen for full-accessibility.

**Comment by Misplon** [comment]
@adiraomj Thanks for raising this challenge. 

Do you know why this behaviour doesn't happen on first touch? It seems to me that it only happens on second touch.

We might need another issue report but I've also noticed that on first load, the sub-menu background doesn't cover the link. When I refresh the page, the issue resolves. Are you able to replicate this?

To see both questions I'm raising, please, see my Xcode Simulator video: https://dl.dropboxusercontent.com/u/3072682/north-menu-ios-simulator.mp4

**Comment by adiraomj** [comment]
@Misplon I will test out the main menu thoroughly tonight and try to fix most issues. :)

**Comment by Misplon** [comment]
Awesome :)

**Comment by Misplon** [comment]
This now looks to be resolved. Nicely done.
