### ISSUE TITLE
Header flickers on scroll in Safari

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#142]
The header flickers on scroll in Safari, both mouse wheel and track padding scrolling cause this (sometimes there is a difference). For a video, see:

https://dl.dropboxusercontent.com/u/3072682/north-header-flicker-issues.mp4

Thread reporting the issue is here:https://siteorigin.com/thread/north-theme-banner-flickers-when-scrolling-updown/#comment-96214. Further details can be found in the thread.

**Comment by Misplon** [comment]
@adiraomj Not sure if Greg mentioned to you but the plan is to only assign an issue once someone is working on it. When you have a moment, could you perhaps take this one on. Let me know if I can help with anything.

**Comment by adiraomj** [comment]
@Misplon thanks for the update. :) I will assign myself when I start working on this.

**Comment by adiraomj** [comment]
@Misplon I think #144 solves this problem. Can you confirm? Thanks.
