### ISSUE TITLE
Add breadcrumb without page title

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#143]
Consider allowing the breadcrumb to display even if the page title has been disabled.

**Comment by adiraomj** [comment]
@gregpriday go ahead with this?

**Comment by Misplon** [comment]
@gregpriday Quick bump. Thanks.

**Comment by Misplon** [comment]
@gregpriday Keen to proceed with this user request?

**Comment by gregpriday** [comment]
Sorry for missing this guys. Yeah, +1 from my side.
