### ISSUE TITLE
Add the ability to enable sticky menu and scroll to top for mobile devices

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#146]
For whatever reason, these two settings are disabled on mobile devices. It makes very little sense not to give the user the option of at least enabling them.

**Comment by Misplon** [comment]
@AlexGStapleton We're currently working through some decent size challenges with sticky on mobile: https://github.com/siteorigin/siteorigin-north/issues/126. We'll get it back into the theme as soon as @gregpriday is able to work on the issue again. The issues were bad so we disabled it for now. Let's rather work the issue from the existing #126.
