### ISSUE TITLE
Checkout button on cart page doesn't seem to work anymore

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#147]
I'm not sure if this is related to the new WooCommerce update or not but for whatever reason the checkout button on the cart page doesn't do anything when clicked. :(

![](https://i.imgur.com/9wGrpU5.png)

**Comment by Julianneaguilar** [comment]
i am having the same problem

**Comment by gregpriday** [comment]
@adiraomj - can you take a look at this?

**Comment by adiraomj** [comment]
Sure

**Comment by AlexGStapleton** [comment]
[Couple more people have reported this issue](https://siteorigin.com/thread/north-theme-checkout-button-in-cart-does-not-work/).

Not sure what caused this but a fix for this needs to be released asap.

**Comment by Misplon** [comment]
I'm sure @adiraomj will have further info. for us when he's back online.

**Comment by gregpriday** [comment]
I'll push an update for this tonight.
