### ISSUE TITLE
SASS Compiler

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/siteorigin-north#15]
@gregpriday, on this [commit](https://github.com/siteorigin/siteorigin-north/commit/57c715ab4eff1b5401fd813a8e5c5bfd6b66c061), I guess you compiled the SCSS and It din't compile properly [here](https://github.com/siteorigin/siteorigin-north/commit/57c715ab4eff1b5401fd813a8e5c5bfd6b66c061#diff-0380fb544d4fe68e179c828ee2dbe149R63), [here](https://github.com/siteorigin/siteorigin-north/commit/57c715ab4eff1b5401fd813a8e5c5bfd6b66c061#diff-0380fb544d4fe68e179c828ee2dbe149R157) & [here](https://github.com/siteorigin/siteorigin-north/commit/57c715ab4eff1b5401fd813a8e5c5bfd6b66c061#diff-0380fb544d4fe68e179c828ee2dbe149R165).

Check out our [discussion](https://github.com/siteorigin/siteorigin-north/pull/11#discussion-diff-47522235R86).

**Comment by gregpriday** [comment]
I've started using build script in `build:dev` mode. I assume this is using the version of SASS that I have in the command line, which is currently `Sass 3.4.20 (Selective Steve)`.

What are you using to compile the SCSS files? We probably need to make sure that we're using exactly the same setup.

**Comment by adiraomj** [comment]
Well.. I just started using gulp, so i'm still finding my feet with it. I just followed the instructions in the [README](https://github.com/siteorigin/theme-build/blob/develop/README.md) file to setup my environment and run builds.

So, how do I check which version of Sass has been installed? 

Thanks for the help.

**Comment by adiraomj** [comment]
guess i'm running version [3.3.2](https://github.com/sass/node-sass/blob/master/package.json#L4)

**Comment by gregpriday** [comment]
I'll see what I can do with the configuration to sort this out. Alternatively, is there anything we can change in the SCSS files to make sure they're compiled the same way across all versions?

**Comment by gregpriday** [comment]
So it seems like changing `@at-root body.responsive#{&} {` to `@at-root body.responsive & {` causes the CSS to compile properly. I've never used at-root before, but after reading the docs, it seems like the second syntax should be the valid one.

Let me know if I'm missing something here though.

**Comment by adiraomj** [comment]
Initially I did try `@at-root body.responsive & {` but it compiles to `body.responsive .woocommerce.single `.

What we need is `body.responsive.woocommerce.single `. Basically the classes `responsive`, `woocommerce` and `single` are associated with the body element.

Do you get what I mean? :)

**Comment by adiraomj** [comment]
Sorry, the version I mentioned [above](https://github.com/siteorigin/siteorigin-north/issues/15#issuecomment-168179863) is the libsass version. 

I'm also using  `Sass 3.4.20 (Selective Steve)`.

sorry about that.

**Comment by adiraomj** [comment]
@gregpriday. please check the version of libsass you are using. 

Check out this [issue](https://github.com/sass/libsass/issues/1491).

Seems like the problem has been sorted out in libsass version 3.3.

**Comment by gregpriday** [comment]
Aaah, there we go. I just removed all the old node modules and did a full reinstall of the build packages. It compiles properly now.

I'll commit the reverts to the changes I made shortly.

**Comment by gregpriday** [comment]
Here's the revert, can you double check this is compiled properly now?

https://github.com/siteorigin/siteorigin-north/commit/7ea0f6a1984800d35c42e8ca2bb18af9704dcff0

If it has, feel free to re-close this issue.

**Comment by adiraomj** [comment]
Everything seems to be in order.
