### ISSUE TITLE
Page Template Setting: Featured Image Sizes

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#162]
@adiraomj, is there any way we can make the featured images more dynamic? If you change from sidebar to no sidebar on the blog page for example, the featured image is no longer container full-width. Any ideas?

**Comment by Misplon** [comment]
Before we had Page Template Settings it was easier. The method we used in Vantage was [as follows](https://github.com/siteorigin/vantage/blob/develop/functions.php#L77). Perhaps we can do that for Page Template Settings. Not for full screen width but just for regular container width, sidebar and no-sidebar.

**Comment by adiraomj** [comment]
@Misplon what dimensions do we use? the post thumbnail has been set to [650x650](https://github.com/siteorigin/siteorigin-north/blob/develop/functions.php#L43). 

How about 1040x650 for the no-sidebar layout?

**Comment by Misplon** [comment]
Sounds good.
