### ISSUE TITLE
Mini Cart: Add ability to remove items / adjust quantity

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#166]
I know the theme is minimal by design but without the ability to remove items and adjust the quantity of items, the mini cart (not too sure on what its called) feels limited. It might be a good idea to put these behind settings as the remove items button might not be desirable for certain people.

Regarding the icons.  An X, plus and minus should fit more in line with the themes minimal design rather than use the base WooCommerce styling / buttons.

**Comment by adiraomj** [comment]
We could consider adding a remove button next to items. The quantity buttons may make the widget seem too cramped. What do you think @Misplon @gregpriday?

**Comment by AlexGStapleton** [comment]
I think something as simple as this would be fine:
![](https://i.imgur.com/Hr4YMYb.png)

Excuse the poor example but I wanted to quickly throw something together. The X would be the same color as the remove button on the checkout - meaning very faint. It could also be a good add a hover for the plus or minus so that they're faint also until you hover on the item.

**Comment by adiraomj** [comment]
@AlexGStapleton neat minimal approach.

**Comment by Misplon** [comment]
Thanks Alex. @adiraomj looks great, let's implement.

**Comment by Misplon** [comment]
@adiraomj If possible, let's look at getting this featured added for the next release in two weeks time.

**Comment by adiraomj** [comment]
@Misplon Sure thing. I'll get this done in a couple of days.

**Comment by Misplon** [comment]
Adi, quick bump to prio 1. Thanks :)

**Comment by Misplon** [comment]
@adiraomj Should we proceed with this one? Thanks :)

**Comment by Misplon** [comment]
@AlexGStapleton You cool with just the remove icon or you still want us to add quantity up and down? What's the standard on big ecommerce sites?

**Comment by AlexGStapleton** [comment]
I've had a look around and there aren't many mini-carts so this was quite tricky. Based on what I've seen though, the quantity options are a bit much and a remove option is enough.

[Toys R Us](http://www.toysrus.com) doesn't provide any options:
![](https://vgy.me/XTIdG5.png)

[Asos](http://www.asos.com) only shows a removal option.
![](https://vgy.me/wgJ1YB.png)


[Macys](https://www.macys.com) only shows removal options upon hoving over a cart item.
![](https://vgy.me/j3JEjN.gif)


Unrelated but victoriassecret.com has a really fancy "shopping bag" instead of a mini cart.  Can't really compare it though.

**Comment by Misplon** [comment]
Nicely done! Epic research man, gifs and all! Props. Ok sweet, will close then, we'll stick with the remove icon for now across our themes with mini-cart.

**Comment by therichpost** [comment]
**Hello to all, please check this image in attached link and hope this is the perfect solution.**
[Woocommerce mini cart add change quantity button](https://therichpost.com/woocommerce-mini-cart-add-change-quantity-button)
