### ISSUE TITLE
Add post format styling

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#168]
Add post format styling. Ideally, we shouldn't have post formats added if we haven't added a matching style. _s have removed post formats from functions recently.

Let's plan out what we can do for each of the formats currently enabled.

**Video:** https://github.com/siteorigin/influence/blob/develop/content-video.php

**Gallery:** Replace Featured Image with gallery just as we did with the video in the above reference.

That just leaves Aside, Image, Quote and Link in terms of the ones we have enabled.

**Comment by Misplon** [comment]
We can leverage these styles for all themes.

**Comment by adiraomj** [comment]
@Misplon can you please check if the function is working in influence. I pasted a YouTube URL in my content.  It did not work for me.
