### ISSUE TITLE
Menu Overlaps Content page setting doesn't work

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-north#17]
The menu doesn't overlap the content and there's a page jump when the user scrolls down the page slightly.

**Comment by adiraomj** [comment]
Just wondering what `Overlaps Content` is expected to do. All I see is a change in the opacity of the `#masthead`. I think a description would be helpful.

**Comment by gregpriday** [comment]
I'll take a quick look at this. I think it might actually be a quick fix.
