### ISSUE TITLE
Sidebar Width (setting): When set to 0% the sidebar will extend greatly

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#172]
I know the title is horrible but this is a weird issue. A user has reported (and I've managed to replicate it) that when you set the sidebar width setting to 0 it'll extend the sidebar dramatically and cause a lot of white space if you have a number of widgets in your main sidebar widget area.

Here's a reference gif:
![](https://i.imgur.com/DFPbmc9.gif)

It's not the best example but it should display what is happening. The best course of action might be to either set a minimum amount or set 0 to output as display: none; instead.

**Comment by AlexGStapleton** [comment]
Should this issue remain open while the PR isn't merged?

**Comment by Misplon** [comment]
Technically, yes. No good reason for closing other than I sometimes forget to come back and close. It also frees things up a little. Have the issue in one place.
