### ISSUE TITLE
Don't use select styles on admin bar

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-north#174]
A very minor change. As a general practice, we shouldn't have any styling that influences the admin bar. Selecting text in the admin bar gives it the theme's background color.

![screen shot 2016-07-18 at 11 06 16 am](https://cloud.githubusercontent.com/assets/1126859/16910231/d28ad3f4-4cd7-11e6-9a88-fdc560c0d3b0.png)

We need some CSS that removes this.

**Comment by gregpriday** [comment]
A little note - this is only on the frontend. Not in the backend.

**Comment by Misplon** [comment]
`#page ::-moz-selection {
  background-color: #c75d5d;
  color: #fff; }

#page ::selection {
  background-color: #c75d5d;
  color: #fff; }`
