### ISSUE TITLE
Theme Setting: Add the ability to use excerpts

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#176]
it's impossible to use excerpts in North. This shouldn't be the case and we should add a theme setting in the blog settings group that will allow the user to decide between full or excerpts. As per Andrews recommendation, Archive Post Content would be a good label for this field. 

It would also be a good idea add a setting that will allow the user to display (or not) the continue reading button if the excerpt is used.

**Comment by Misplon** [comment]
If we want to provide full functionality here, I suggest the following:

**Label:** Archive Post Content: 
**Description:** Choose how to display your post content on blog and archive pages. Select Full Post Content if using the "more" quicktag.
**Options:** 
Full Post Content
Post Excerpt

**Label:** Read More Text
**Description:** The button text displayed when posts are split using the "more" quicktag.
Text field.

**Label:** Post Excerpt Length
**Description:** If no manual post excerpt is added one will be generated. How many words should it be?
Number field default to 55

**Label:** Post Excerpt Read More Link
**Description:** Display the Read More Text below the post excerpt. Only applicable if Post Excerpt has been selected from the Archive Post Content setting.
Checkbox, enabled by default

**Comment by AlexGStapleton** [comment]
@Misplon Based on the  [you mentioned](https://siteorigin.slack.com/archives/support/p1469034224000022), I don't think a dedicated field would be worth wild.

Huge fan of the Post excerpt length suggestion though.

**Comment by Misplon** [comment]
Quite right. 

I know from Vantage requests that we have been asked several times for the ability to add a Continue reading button with excerpts. That's added with a function so there wouldn't be any way for someone to change that string if they were using the excerpt setting. It might also be handy to be able to set the default for this string.

**Comment by Misplon** [comment]
Or we could leave the Continue reading text setting out and ask to use Loco Translate if it's requested.
