### ISSUE TITLE
Add button styling to pagination

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#179]
Our pagination doesn't look styled at the moment. Let's put something together.

![north-pagination](https://cloud.githubusercontent.com/assets/789159/17105163/5f5bb57e-5286-11e6-991a-e8daa189e229.png)

**Comment by adiraomj** [comment]
@Misplon for some reason, the styling that we are using does not seem to applied in the screenshot you added. This is what I am seeing.

![pagination](https://cloud.githubusercontent.com/assets/3372029/17127053/3dfd0a50-5320-11e6-9dd7-c22b7697800a.png)

They seem to have a nice minimal touch now.

This is where the pagination is styled https://github.com/siteorigin/siteorigin-north/blob/develop/sass/site/primary/_pagination.scss

**Comment by adiraomj** [comment]
Also the previous and next links use icons as shown in my screenshot above.

This is the function that does this https://github.com/siteorigin/siteorigin-north/blob/develop/inc/template-tags.php#L67-L96

**Comment by gregpriday** [comment]
Yeah, the version @adiraomj posted is how it's meant to look. Do you by any chance have something like Page Navi installed @Misplon?

**Comment by Misplon** [comment]
@adiraomj Thanks, this is my fault for the way I created a loop-blog.php template in a child theme.

Can we perhaps add a loops folder to North and add a loop-blog.php template so that the Post Loop template can be deployed in North. Same setup as Vantage has with loops.
