### ISSUE TITLE
Author Box: Add additional styling

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#184]
Not quite sure what yet but let's add additional styling to the author box.

**Comment by AlexGStapleton** [comment]
I'm not too sure what you could add styling wise. I posted the two other issues that I could come up with but they're not styling related. Maybe the hook one is. S:

Issues:
https://github.com/siteorigin/siteorigin-north/issues/185
https://github.com/siteorigin/siteorigin-north/issues/186

**Comment by adiraomj** [comment]
@Misplon any ideas on what to do? 

One idea is to remove the border and use `background: #eee` for the author box. This should enhance it's minimal look. Other than this the major factor that will impact the look is the fonts selected by the users.

**Comment by Misplon** [comment]
Let's give that a try. Thanks :)
