### ISSUE TITLE
Consolidate customize settings groups that we didn't add into more relevant sections. 

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#199]
We should move WordPress customizer settings like Background Image and Colors into our settings if possible. This way it'll make the overall customizer experience more streamlined as the settings will be in more relevant locations. For example, the background color setting (found in colors) would be better suited in Theme Settings > Page Structure (although Page Structure would need to be renamed to just page). The same applies to the background image setting.

**Comment by Misplon** [comment]
That last time I saw this come up on the Theme Review Team Slack channel it was split down the middle with one admin being cool with this idea and another being dead against it. Have you seen any big themes move these sections? We'd need to check where TRT landed on this, not sure if it's in the guidelines yet.

**Comment by gregpriday** [comment]
It might be nice to move the settings around, but I'd prefer to keep things like this as default as possible. A new ruling in the theme review team could result in us having to undo this (and change the docs). We're also opening ourselves up to WordPress version conflicts my moving around default stuff.

All of this makes it not worth doing the move.

**Comment by AlexGStapleton** [comment]
That's fine. :)

At least I have something to reference when someone brings this up again. ;)
