### ISSUE TITLE
Option to have external SVG instead of inline

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-north#2]
All SVG is loaded inline. This is to make it possible to animate the SVG image using CSS3 animations.

There are cases, when a user might prefer to forgo these animations to have the SVG files be externally hosted. This should be a theme option.

**Comment by adiraomj** [comment]
I have not worked with svg before, so for the sake of clarity; 

In the settings I have to add options for links to the svg icons for the menu, close search and scroll to top. After which I should use them in the theme like [this](https://css-tricks.com/svg-use-external-source/).

**Comment by gregpriday** [comment]
I would have originally suggested using an IMG element, but `use` with an external reference is a much better idea. With this, we should be able to keep the CSS3 animations and the options to change the colors of the SVG elements.

**Comment by adiraomj** [comment]
I have added the options for svg icons and used them in the templates. 

Should I also add options to change the icons colors? If yes , should I also apply the changes to the default icons included with the theme?

A link to the [branch](https://github.com/adiraomj/siteorigin-north/tree/svg-icons), if you wanna have a look.

**Comment by gregpriday** [comment]
I like what you've done in that branch. We can add icon colour changing options at a later stage. I prefer the idea of getting a theme mature and having some idea of how people are using it before adding customization options like this.

I see you've added svgxuse - https://github.com/Keyamoon/svgxuse? Do you know what browser support for `<use>` in SVG is like these days? I couldn't find any information on this.

**Comment by adiraomj** [comment]
Thanks @gregpriday. Hope this helps. https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use

I will check everything and send a PR tomorrow.

**Comment by adiraomj** [comment]
@gregpriday check out this repo https://github.com/jonathantneal/wp-svg-spritemap/. It is more or less exactly what we need.

**Comment by gregpriday** [comment]
That's an interesting looking plugin, but I think it would be a bit too heavy to add that to North or the settings framework right now. Maybe one day though.

Is there no way to for us to implement this without using spritemaps? So just letting users upload individual SVG files for each icon? I know there's a bit of a performance hit for this, but that's worth it if it makes things easier for users.

**Comment by adiraomj** [comment]
Came across this Gist https://gist.github.com/Lewiscowles1986/44f059876ec205dd4d27. What do you think? 

Does everything we want. It does not show the svg in the customizer. I guess we can fix that.

**Comment by gregpriday** [comment]
The only thing I'd be worried about with using all these filters to enable SVG support is that we'd be opening ourselves up to a lot of potential plugin conflicts, etc. It's generally best to try avoid that.

So here's one other option we have, we could let users upload their own custom icons in either PNG or JPG formet, which WordPress obviously supports natively. Then we could incorporate support for a plugin like [SVG Support](https://wordpress.org/plugins/svg-support/) to let users upload custom SVG icons.

This might be the best solution, as long as that SVG Support plugin works with customizer image select fields. Do you want to give that a try?

**Comment by adiraomj** [comment]
Ok. Will do it.

**Comment by adiraomj** [comment]
Just wondering.. Since we are moving in a fresh direction on this issue. Do I just make changes to the existing PR or send a new PR?

**Comment by gregpriday** [comment]
If it's different enough that you'd like to start with a fresh branch from
develop, then you can start a new branch and new PR, else feel free to
continue with the existing branch and PR.

**Comment by adiraomj** [comment]
The SVG Support plugin allows us to upload & select svg files. However they do not appear in the customizer fields. 

I have posted a support question [here](https://wordpress.org/support/topic/display-svg-in-customizer?replies=1)

**Comment by Misplon** [comment]
@adiraomj Any news on this one? Have we completed this task? Thanks :)

**Comment by adiraomj** [comment]
@misplon I have added support for the [SVG Support](https://wordpress.org/support/plugin/svg-support) plugin. Please have a look at this [PR](https://github.com/siteorigin/siteorigin-north/pull/14). Let me know if you want to merge it, I will fix all merge conflicts. :)

**Comment by gregpriday** [comment]
I'll chat to Andrew about the best way for us to implement this. We just
need to make some changes to make it a little more user friendly.
