### ISSUE TITLE
Style form elements in post content

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-north#20]
At the moment, form elements in post content aren't very well styled. They still have the default styling that came with [Underscores](https://github.com/automattic/_s).

Ideally form elements should have fairly similar styling to the comment form.

You can see an example of the poor styling on a password protected form.

![screen shot 2016-01-06 at 1 52 27 pm](https://cloud.githubusercontent.com/assets/1126859/12142216/fb1fee22-b47e-11e5-88f5-c9fb01dcddc3.png)

Another place to look would probably be a Contact Form 7 form.

**Comment by adiraomj** [comment]
I have sent a PR. I have covered styling for contact form 7. Just check it and let me know if you would like any changes.
