### ISSUE TITLE
Customize:  When font variant is set to blank, an empty value is output

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#201]
We should revert to normal when no option is selected, or output nothing.

![](https://i.imgur.com/O83pSlQ.png)

**Comment by adiraomj** [comment]
This is a settings framework issue.

**Comment by AlexGStapleton** [comment]
Good to know. Thanks mate! :)

**Comment by AlexGStapleton** [comment]
No reason to really keep this open when it's related to the settings framework.
