### ISSUE TITLE
Output North WooCommerce assets globally

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#214]
WooCommerce widgets can be used sitewide but our assets are only output on WooCommerce specific pages. This means things like the Quick View won't work on, for example, the homepage if they are added by a widget.

For reference, the specific assets I'm referring too are woocommerce.js and woocommerce.css

**Comment by AlexGStapleton** [comment]
Actually, this is a massive change as quick view relies on the .woocommerce body_class.

**Comment by Misplon** [comment]
@adiraomj Before I assign priority to this, please, can you take a look at the scope challenges here and let us know what you'd like to do. Thanks man.

**Comment by adiraomj** [comment]
@Misplon I should be able to do this.

**Comment by Misplon** [comment]
Thanks.

**Comment by Misplon** [comment]
@adiraomj Quick look here when possible.

**Comment by Misplon** [comment]
@adiraomj Any ideas here?

**Comment by Misplon** [comment]
@AlexGStapleton I can take this on. I'm guessing the following needs to happen:

* WooCommerce widget styling needs to be removed from the `.woocommerce` parent selector in the `woocommerce.cs`s file.

**Comment by AlexGStapleton** [comment]
Correct. It also needs to be output on all pages also. Ideally, keep the woocommerce.css separate still so the CSS is only present if WooCommerce is active.

**Comment by Misplon** [comment]
Should be resolved now. Anything comes up, let me know.
