### ISSUE TITLE
Top Bar Widget Area

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#217]
Much the same as the [masthead widget area in Vantage](https://github.com/siteorigin/vantage/pull/144), we should add a widget area for the Top bar in North. My reasoning behind this is it's not uncommon for eCommerce related websites to include a sub menu (typically contains account related links) above the regular navigation and social icons, etc.

Allowing the user to replace the top bar contents with a layout builder will add a new level of control over this space.

[Initial Suggestion](https://siteorigin.slack.com/archives/themes/p1476823997000042)

**Comment by Misplon** [comment]
This will be epic. Good idea.
