### ISSUE TITLE
Smooth Scroll: Limit to specific areas, class and add a setting for more selectors

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#218]
As per the [conversation on slack](https://siteorigin.slack.com/archives/themes/p1477272269000087). The following should be done to the smooth scroll:

The Smooth scroll will be limited to the header, sidebar and footer. We'll add a settings field that will allow the user to define a selector for custom areas and widgets. The user will also be able to apply smooth scroll by applying .so-scroll to a link or child (as in, .so-scroll a, .so-scroll).

This reduces the chance of compatibility issues while also giving far greater control (when compared to how it originally was) to the user.

**Comment by Misplon** [comment]
@AlexGStapleton Do you still want this issue attended to?

**Comment by AlexGStapleton** [comment]
I think we can put it on the backburner for the time being as I haven't actually seen reports of this being an issue.

Consider reopening later on if this starts to become a more major occurrence.

**Comment by Misplon** [comment]
Perfect.
