### ISSUE TITLE
Close the mobile menu if the resolution increases beyond the breakpoint

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#222]
Not a normal use case, but, for users testing on their desktop it would be neater if we closed the mobile menu if the user increases the viewport beyond the breakpoint setting or default if no setting is set. Small task to complete.

To see this issue:

1. Change browser window to mobile.
2. Open mobile menu.
3. Resize browser to full-width.

Ideally, at this point, we should close the mobile menu to avoid the below.

<img width="1426" alt="close-mobile" src="https://cloud.githubusercontent.com/assets/789159/19865076/6d73b520-9fa3-11e6-8c31-c7a929df3336.png">

**Comment by adiraomj** [comment]
This should not happen. I'm also unable to replicate it.

https://github.com/siteorigin/siteorigin-north/blob/develop/inc/settings.php#L962-L966 takes care of the issue.

Can you please check the CSS on your front end when the mobile menu appears beyond the breakpoint. Thanks
