### ISSUE TITLE
.wc-proceed-to-checkout is hidden

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#223]
When [.wc-proceed-to-checkout is hidden](https://github.com/siteorigin/siteorigin-north/blame/develop/sass/woocommerce/_cart.scss#L127) certain payment methods, such as [PayPal for WooCommerce - angelleye](https://en-au.wordpress.org/plugins/paypal-for-woocommerce/), won't be usable on the cart page as it's not visible.

Is .wc-prooced-to-checkout hidden for a specific reason?

**Comment by Misplon** [comment]
@adiraomj Can you please, take a look at this. Any idea why it was originally hidden? Thanks.
