### ISSUE TITLE
Comment form fields aren't responsive

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#224]
Outside of the comment itself, the guest comment fields aren't responsive. Here's what the comment form looks like at 375x540px:

![](https://i.imgur.com/NoAFeIz.png)

667x375 (horizontal iPhone 6):
![](https://i.imgur.com/F3ak5xz.png)

Please note that this also affects the review form.
![](https://i.imgur.com/bMLmGl4.png)

For a demonstration, please [refer to the theme demo](https://demo.siteorigin.com/north/2015/11/13/oh-what-a-sky/#more-38).

SASS references, [_comments.scss](https://github.com/siteorigin/siteorigin-north/blob/develop/sass/site/primary/_comments.scss#L88), [woocommerce.scss](https://github.com/siteorigin/siteorigin-north/blob/develop/sass/woocommerce/_reviews.scss#L45)

**Comment by Misplon** [comment]
@alex, is the iPhone 6 landscape issue not because the sidebar is present at that resolution? If you scroll up, you possibly have a sidebar there which is why the comment form isn't full-width.

**Comment by Misplon** [comment]
@AlexGStapleton I've changed the behaviour for below 480px. Pull `develop` and let me know if you want further adjustments. Thanks :)

**Comment by AlexGStapleton** [comment]
@Misplon Yes, technically, it's due to the sidebar, it's still unreadable though.

That's much better by the way. :)

**Comment by Misplon** [comment]
@AlexGStapleton What we could do then is push these adjustments to `768` or `880px` and not just `468`. You keen for that?

**Comment by AlexGStapleton** [comment]
Yes. 768px should be fine. :)

**Comment by Misplon** [comment]
Resolved via https://github.com/siteorigin/siteorigin-north/commit/439068baeff04412ec9dc27d5b7335fedc163072
