### ISSUE TITLE
WooCommerce: Make the mini-cart visible during the checkout process

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#225]
Users have requested the mini-cart stay visible during checkout. I realise this isn't the best usability practice but it seems enough requests have come up to consider it.

**Comment by Misplon** [comment]
We could add this to compensate: https://github.com/siteorigin/siteorigin-north/issues/226.

**Comment by adiraomj** [comment]
Do we make this optional with a setting?
