### ISSUE TITLE
WooCommerce: Add a stripped checkout option

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#226]
Add a default off setting for a stripped checkout. The stripped checkout would remove the main menu and search icon, leaving the logo. Footer widgets would be removed, leaving only the copyright. The sidebar would be removed and the content container constrained and centered.

**Comment by gregpriday** [comment]
Is this not possible with a page template?

**Comment by adiraomj** [comment]
A page template would be better than a setting. We could call it **Stripped Template**.

**Comment by Misplon** [comment]
@adiraomj Ok cool, I'll get on this.

**Comment by Misplon** [comment]
@AlexGStapleton The stripped page template has been added to the develop branch. Check it out when you have a moment. We'll aim for a North release on Monday.

**Comment by AlexGStapleton** [comment]
Just tried it. Looks good! 👍  Although I really don't agree with it being a template - it would be better as a page layout.
