### ISSUE TITLE
Twitter Embeds not working

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/siteorigin-north#23]
Twitter links in the content are not displaying an `iframe` on the site.

The twitter iframe is visible in the Editor.

**Comment by Misplon** [comment]
@adiraomj Could you perhaps explain how to replicate this? I tried creating a Tweets by me widget, I also embedded a Tweet, both seem to be fine.

Thanks :)

**Comment by adiraomj** [comment]
Seems to be working now. I think something must have been off with my local setup.
