### ISSUE TITLE
Hide Premium teaser on about when premium active

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#233]
We shouldn't should the SiteOrigin Premium teaser on the about page when SiteOrigin Premium is active.

![](https://i.imgur.com/QHoWkPF.png)

**Comment by Misplon** [comment]
For sure. Can you log in Settings Framework for us?

**Comment by AlexGStapleton** [comment]
Oh. My mistake.

**Comment by Misplon** [comment]
No problem, thanks :)
