### ISSUE TITLE
Mobile Menu: Add Scroll when sticky menu is being used and menu exceeds vh.

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#235]
If the mobile menu is sticky and there're more menu items than can fit on the screen at once, you won't be able to see all menu items as you cannot scroll the mobile menu.

![](https://i.imgur.com/rnbIQCh.gif)

[Reference](http://alex.siteorigin.net/sample-page/)

**Comment by adiraomj** [comment]
We worked on the same issue before #63. The fix from there seems to work fine on iOS. But giving problem with Android. I'll work on a fix. :)

**Comment by AlexGStapleton** [comment]
Oh, that does appear to be related - my bad.

I provided a temporary solution to the user that looked like so:

```
#mobile-navigation {
	overflow-y: scroll;
}
```

Maybe run a check to see if the mobile menu exceeds the browser (height wise) and apply overflow-y: scroll if it does? That's likely not the best fix but a temporary solution is better than no solution imo.
