### ISSUE TITLE
Integration: Add Support for Max Mega Menu

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#241]
We should run some tests to ensure we integrate well with [Max Mega Menu](https://en-au.wordpress.org/plugins/megamenu/) (100k).

**Comment by AlexGStapleton** [comment]
User approached and stated he was having issues with using the Max Mega Menu columns. The issues was due to the submenu items being limited to 100%. The sub menu links also had issues with the links being set a hard width but that might be more related to max mega menu.

The resulting CSS for the conversation (to resolve the column issue) was:

```
.main-navigation ul ul li {
	max-width: none;
}

.main-navigation ul ul a {
	white-space: normal;
	width: auto !important;
}
```

Max Mega Menu adds about a dozen or so classes so it should be pretty easy to bypass our general CSS with a class specific selector.

**Comment by Misplon** [comment]
@adiraomj Let's hit this one first in our next North run.
