### ISSUE TITLE
Initial Load Smooth Scroll - account for page load

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#244]
When widgets like the SiteOrigin Hero widget are present on the page and a user has navigated to this page via a link with a fragment (example.com/example-page/#test), chances are the user will end up in the wrong location due to the hero widget setup not being complete. To avoid this issue we should either account for this or put a delay on it. The latter, while easier, seems to be very unreliable (#243) as such the former is a more consistent but trickier solution.

Another option might be to do the initial check, and then another check a second later but that is likely overkill. This would also require the ability to change the location during scroll (which I'm not certain is possible as I've never tried it).

**Comment by Misplon** [comment]
Any chance you have a live link for this problem? Does putting the anchor in the row not resolve the issue?

**Comment by adiraomj** [comment]
Would using `window.load` solve the problem ? This way the function would run only after the page has completely loaded.

```
( function($) {
	$(window).load( function() {
		// Handle smooth scrolling
		if ( siteoriginNorth.smoothScroll ) {
			$( '#site-navigation a[href*="#"]:not([href="#"])' ).add( 'a[href*="#"]:not([href="#"])' ).not( '.lsow-tab a[href*="#"]:not([href="#"]), .wc-tabs a[href*="#"]:not([href="#"]), .iw-so-tab-title a[href*="#"]:not([href="#"])' ).northSmoothScroll();
		}
	} );
} )(jQuery);
```

**Comment by AlexGStapleton** [comment]
Hm, that would work yes but depending on the page itself load may be triggered for a ridiculous amount of time. I would say try it, and if people don't like it, we'll just revert it.
