### ISSUE TITLE
Post meta comments link: Smooth scroll it

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#248]
Add the post meta comments link to the smooth scroll list. `.comments-link a[href*="#"]:not([href="#"])`. It will smooth scroll that link but most importantly, it'll offset the header.

**Comment by adiraomj** [comment]
As of now, smooth scroll applies to all links on the page containing `#`. 
https://github.com/siteorigin/siteorigin-north/blob/develop/js/north.js#L417

We can revisit this if we add more specificity to the links to which smooth scroll is applied.
