### ISSUE TITLE
Font Theme Settings: Add descriptions

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#251]
It's not really clear what "Dark Text" or "Medium text" is for so to prevent confusion, we should provide a brief example of what the text color is used for.

**Comment by adiraomj** [comment]
Suggestions:

**Dark Text Color** : Applied to headings and titles
**Medium Text Color** : Default color applied to all text
**Light Text Color** :  Applied to comments and breadcrumbs
**Meta Text Color** : Applied to bylines
**Menu Text Color** : _self-explanatory_
**Menu Text Hover Color** : _self-explanatory_

What do you guys think?

**Comment by AlexGStapleton** [comment]
Doesn't Dark Text color also apply to hover? If not, why not just rename it to header color?

**Comment by Misplon** [comment]
It might be applied to other elements in the future so let's go with the explanation and see if that helps the problems. I'll also update docs.
