### ISSUE TITLE
Change WooCommerce PayPal Gateway checkout icon

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#253]
Find out if we can change this icon. and if so, change it to something that looks better overall.

![](https://i.imgur.com/7Gil3C2.png)

**Comment by Misplon** [comment]
This looks to be ok in my version. @AlexGStapleton Please, can you check.

<img width="273" alt="paypal" src="https://cloud.githubusercontent.com/assets/789159/22401388/e23c9bc4-e585-11e6-9cf3-755b404f8b97.png">

**Comment by AlexGStapleton** [comment]
I'm still seeing this. Hm. The url of the image is https://www.paypalobjects.com/webstatic/en_AU/mktg/logo/Solutions-graphics-1-184x80.jpg for me, what is it for you?

**Comment by Misplon** [comment]
Ahh! PNG:
https://www.paypalobjects.com/webstatic/mktg/Logo/AM_mc_vs_ms_ae_UK.png

Cool, will try to standardise it.

**Comment by Misplon** [comment]
Forgot to hash the issue number. Pull and check this: https://github.com/siteorigin/siteorigin-north/commit/4be7162edbf5090d224450940dbaa84a08e74ac5.

**Comment by AlexGStapleton** [comment]
Oh. I'm blind - how did I not see that it was a jpg. :facedesk:

**Comment by AlexGStapleton** [comment]
All good! 👍
