### ISSUE TITLE
Stripped Template: Disable scroll to top

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#254]
The stripped template is a very light version of North. The scroll to top button isn't light and stands out a lot.

**Comment by Misplon** [comment]
@adiraomj Quick check for: https://github.com/siteorigin/siteorigin-north/commit/96138314cee268b5dea3a55d1b91058a79f9be9e. Meant to do two commits hence the incorrect commit message. Thanks.

**Comment by adiraomj** [comment]
Looks good
