### ISSUE TITLE
Include screen reader text div when using custom responsive menu text

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-north#256]
For this line, we should probably still have the screen reader text div, even when the user enters a custom responsive menu text.

https://github.com/siteorigin/siteorigin-north/blob/648da83bfc7369cdbc11a9004479892e2f18fcd5/header.php#L54

**Comment by Misplon** [comment]
Sweet :)

**Comment by Misplon** [comment]
@gregpriday https://github.com/siteorigin/siteorigin-north/commit/2b8bd107e63e7a3b70c66e4c1efb02d896f9333e#diff-1c1ae65fe9828eb6d3cee4edacf90018L56
