### ISSUE TITLE
Mini Cart duplicates when you open mobile menu multiple times

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#262]
This can be replicated [in the demo](https://demo.siteorigin.com/unwind/).

![](https://i.imgur.com/t2SFeTv.png)

**Comment by Misplon** [comment]
@AlexGStapleton User reported this so we'll go with their issue number. I'm going to close this unless you're seeing the same issue in North.

**Comment by AlexGStapleton** [comment]
Huh? I don't understand your reply. Can you please elaborate?

I'm seeing the same issue on the demo for North - the above screenshot was taken by me.

**Comment by Misplon** [comment]
No problem. The screenshot and link is for Unwind, this is the North repo. 

In the Unwind repo a user has logged: https://github.com/siteorigin/siteorigin-unwind/issues/105.

**Comment by AlexGStapleton** [comment]
Oh.... well this is awkward.
