### ISSUE TITLE
Customizer CSS: Don't output WooCommerce CSS unless WooCommerce is active

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#263]
We should add a WooCommere check to [siteorigin_north_settings_custom_css()](https://github.com/siteorigin/siteorigin-north/blob/develop/inc/settings.php#L490) to prevent the WooCommerce CSS from being unnecessarily output.

**Comment by Misplon** [comment]
We'd have to manually split up the CSS build output but it's possible.
