### ISSUE TITLE
Minified style.css uses incorrect z-index

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#264]
In the latest release the minified version of style.css isn't using the correct z-index in any situation. For example, the #masthead has a z-index of 5, not 999.

![](https://i.imgur.com/Lyxbmzr.png)

A quick look over the entire file and no z-index is correct - they're all sub 10. I'm unsure if this is an issue with the build script, or just the release so I'm logging this here just to be safe.

**Comment by gregpriday** [comment]
@braamgenis, can you check if there's a way to turn off z-index range reduction (or whatever it's called) in the build script?

**Comment by braamgenis** [comment]
Hrmmm. It'd be weird if they're doing that by default. I'll check.

**Comment by braamgenis** [comment]
Bizarre... They call it **unsafe** in their docs, and then make it the default behaviour...
http://cssnano.co/optimisations/zindex/
