### ISSUE TITLE
Widget Top Bar: Social buttons causing overlap

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#265]
<img width="431" alt="social" src="https://cloud.githubusercontent.com/assets/789159/23333079/15573ac2-fb3a-11e6-82fd-e5ffdadec480.png">

Social network widget inserted into top bar causes overlap.

**Comment by adiraomj** [comment]
@Misplon can you please see if any setting is causing the problem on your setup. 

I have tested with and without sticky menu active. Could not replicate the issue.

![screenshot-so dev 2017-02-26 12-06-40](https://cloud.githubusercontent.com/assets/3372029/23337689/11a5e3be-fc1c-11e6-82e3-dba6d1b94270.png)

**Comment by Misplon** [comment]
@adiraomj Please, check to see that the Text Above field is completely empty, any text in that field will fix this problem. Thanks.
