### ISSUE TITLE
Header colors override widget colors

### ISSUE THREAD

**Issue by Jursdotme** [siteorigin/siteorigin-north#266]
Im not sure if this is to be considered a North theme issue or a general Page Builder issue.

When using custom font colours on a widget the "Dark Text colour" from the customizer overrides the widget specific settings. This should really be the other way around.

Adding this
```css
h1, h2, h3, h4 ,h5 ,h6 {
  color: inherit;
}
```
...fixes the problem by effectively ignoring the setting in the customizer. But having the customizer setting as a fallback when a color is not defined would be better.

**Comment by Misplon** [comment]
Thanks @Jursdotme. Will take a look ASAP and work out the best place to make this fix.
