### ISSUE TITLE
Ensure WooCommerce 2.6 Compatibility 

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#280]
We need to ensure WooComemrce 2.6 compatibility for the time being due to the popularity/reluctantly for people to update ([reference](https://en-au.wordpress.org/plugins/woocommerce/advanced/)).

Here's an error I'm aware of for product pages:
Fatal error: Call to undefined function wc_get_stock_html() in /public_html/dev/wp-content/themes/siteorigin-north/woocommerce/single-product/add-to-cart/simple.php on line 21

[Slack Reference](https://siteorigin.slack.com/archives/C02T5GSNA/p1493712513619912)

**Comment by adiraomj** [comment]
Are you able to replicate the issue with `wc_get_stock_html()`. This is a valid function and is also used in the default WC template. https://github.com/woocommerce/woocommerce/blob/master/templates/single-product/add-to-cart/simple.php#L28
