### ISSUE TITLE
Integration: Add Support for UberMenu

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#283]
Basically the same request as #241

We should run some tests to ensure we integrate well with [UberMenu](https://codecanyon.net/item/ubermenu-wordpress-mega-menu-plugin/154703) (at least 60k).

**Comment by AlexGStapleton** [comment]
[Requested here](https://siteorigin.com/thread/ubermenu-and-north-theme-conflict/) and [reported here](https://siteorigin.com/thread/ubermenu-big-issue-on-mobile/).

Basically, just general functionality issues (inability to scroll, unable to use different menu types) are present.

**Comment by Misplon** [comment]
Cool, might as well do MMM at the same time. MMM has a free version.
