### ISSUE TITLE
Cart: Visually unable to remove all items from cart without refreshing page

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#284]
While it's possible to remove certain items from the cart when on the cart page, it's not possible to visually remove all of them. I say visually because the item is, in fact, being removed but it's not apparent due to it still being present on the page. If you refresh the page, the cart will be empty.

![](https://i.imgur.com/MavE5G5.gif)

This can be replicated on the demo.

**Comment by Misplon** [comment]
Wild!

**Comment by Misplon** [comment]
@adiraomj Think you can check this one out for us?
