### ISSUE TITLE
Increase line-height for product titles

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#285]
We should increase the line-height for product titles as it feels a tad low at the moment.

Currently:
![](https://i.imgur.com/dHlP8V2.png)

After applying 1.1em:
![](https://i.imgur.com/iLRoVyn.png)

**Comment by Misplon** [comment]
https://github.com/siteorigin/siteorigin-north/commit/6a07664728b908da10129d1de6496b61441cfa77
