### ISSUE TITLE
Create WooCommerce cart in menu

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-north#3]
The original design for North has a shopping cart in the menu. This still needs to be implemented.

https://drive.google.com/file/d/0B1NA5KhRaLDDcWRMMnRhMU5oSWc/view?usp=sharing

**Comment by gregpriday** [comment]
This shopping bag icon is already actually in the [North icons](https://github.com/siteorigin/siteorigin-north/blob/develop/css/north-icons.css).

**Comment by adiraomj** [comment]
This is where I have reached for [Large Screens](https://www.dropbox.com/s/yycc8z0b0859lq3/woocart-dropdown.png?dl=0) and [Mobile Screens](https://www.dropbox.com/s/b4smnfyy6ptwv64/woocart-mobile.png?dl=0).

I have to still do some work on the CSS. I wanted to know how you felt about the layout and the elements.

I have added the "View Cart" button and "Subtotal" text which appear in the default Woo Widget. In the image you attached above, it was not present. Please let me know where you stand on this.

In the Mobile view I have added "View Cart" text. Do you feel it's unnecessary ? Also, are you fine with the mobile view design or did you have something else in mind ?

**Comment by gregpriday** [comment]
I really like what you've done with both of those designs. They need a few minor design tweaks (mainly in the padding), but the general idea you've had for both of these is perfect.

**Comment by adiraomj** [comment]
Please check the PR and let me know if anything wrong. ;)

**Comment by gregpriday** [comment]
Merged and resolved :+1:
