### ISSUE TITLE
UberMenu: Selector change causes search alignment issue

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#304]
This is a follow up to #302.

[This line](https://github.com/siteorigin/siteorigin-north/blame/develop/sass/navigation/_menus.scss#L154) causes alignment issues with the search icon. The user stated he was able to resolve this issue by setting it to inline-block (rather than block) but I suspect that's not the ideal fix.

![](https://i.imgur.com/niZwsrT.gif)

**Comment by Misplon** [comment]
That fix is ok for the user if they are using UberMenu. It wouldn't be ideal for a user needing to switch back to the regular menu. Let me take a look. I had thought users would use the UberMenu search and not our search when switching to UberMenu.

**Comment by Misplon** [comment]
Oh dear! Ok, I see. Will push an update for this shortly. My bad.
