### ISSUE TITLE
Mobile Menu: SVG Issue

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#307]
I've received a few reports of an issue with the mobile menu icon. This issue _does_ affect [the North demo](https://demo.siteorigin.com/north/). Here's a copy of one of the reports:

> I'm currently finding that that the hamburger in the mobile page does not animate correctly when you're in the menu on a iPhone.
> I think it is supposed to show a cross, however it seems to be showing something that resembles a tick!

![](https://i.imgur.com/GIcjzQK.jpg)

This appears to be a recent issue as I have only received this reports within the last week. This also apparently also only affects retina devices - although I can't personally replicate it.

**Comment by Misplon** [comment]
Will attend. Thanks man.

**Comment by Misplon** [comment]
@adiraomj Can you take a look for us?

**Comment by Misplon** [comment]
Unfortunately, I just removed those in a commit before this PR: https://github.com/siteorigin/siteorigin-north/commit/42b3454e6a652591517e933fed4462ab1543db81. It looks like something else is the problem. Thanks Adi.

**Comment by AlexGStapleton** [comment]
You can actually replicate this issue in the latest version of FireFox (reported [here](https://siteorigin.com/thread/responsive-burger-menu-is-broken-in-firefox/)). I personally prefer the idea of the new icon based Mobile Menu though.

![](https://vgy.me/5o2bsV.png)
