### ISSUE TITLE
Mobile Menu: Page Jumps won't close mobile menu after clicked

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#321]
[Reported here](https://siteorigin.com/thread/mobile-menu-not-disappear-clicking-floating-one-pager/). I think this is related to #316 

Click a link designed for the current page ([one page links](https://siteorigin.com/one-page-websites-page-builder/)) and the browser will correctly scroll to the correct area but the mobile menu won't close.

[Reference video](https://drive.google.com/a/siteorigin.com/uc?id=1sV9nvHTPV1EcpN8Of_9j-xHoQc6FT-gq)

**Comment by Misplon** [comment]
@adiraomj There is also an error in the console from our recent commit:

`north.js?ver=dev:262 Uncaught TypeError: $(...).hasClass(...).attr is not a function
    at HTMLAnchorElement.<anonymous> (north.js?ver=dev:262)
    at HTMLAnchorElement.dispatch (jquery.js?ver=1.12.4:3)
    at HTMLAnchorElement.r.handle (jquery.js?ver=1.12.4:3)`
