### ISSUE TITLE
WooCommerce: Sidebars spacing cannot be removed due to less specific CSS

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#323]
The WooCommerce sidebar spacing cannot be removed if the specific sidebar is set to not have a sidebar. This is as a result of the no sidebar CSS being less specific than the WooCommerce sidebar spacing selector.

![](https://i.imgur.com/aw8HsuV.png)

**Comment by Misplon** [comment]
Hey Alex where is this happening? What was the test case?

**Comment by AlexGStapleton** [comment]
Open the cart page, head over to the page settings box and set the **Page Layout** to **No Sidebar**.

**Comment by Misplon** [comment]
Bit of an overlapping mess now. Corp is much cleaner in this area. Will probably have to introduce another set of page settings rules with woocommerce prefixes.

**Comment by AlexGStapleton** [comment]
Is it too late to rip the Shop sidebar out and tell people to use something like WooSidebars? :(

**Comment by Misplon** [comment]
Unfortunately, that ship has sailed.

**Comment by Misplon** [comment]
Can't currently re-create, Alex to report back later.
