### ISSUE TITLE
Retina logo appearing as mobile menu icon?!

### ISSUE THREAD

**Issue by frontenddevguy** [siteorigin/siteorigin-north#326]
On North theme, I set the 2x retina logo image.

When in responsive view, this logo is being output in the frontend as an img tag to trigger the mobile menu, which is unexpected behaviour.
I then see 2 logos on the screen. The original one, and the 2x one which has replaced burger menu.
I looked through Customizer but couldn’t see where this could be set.

Even after I delete the retina image in Customizer, it still appears.

You can see it at https://meetami.wpshala.com

**Comment by Misplon** [comment]
Hi @frontenddevguy 

At `Theme Settings > Icons` can you please confirm there is no image/icon set?

**Comment by frontenddevguy** [comment]
Icons! Sorry, I totally overlooked that setting.

**Comment by Misplon** [comment]
Super, glad that helped. All the best.
