### ISSUE TITLE
After pulling db from live site to localhost, button widgets do not open

### ISSUE THREAD

**Issue by frontenddevguy** [siteorigin/siteorigin-north#328]
After pulling my db (with Migrate DB) from live site to localhost, button and call to action widgets do not open.
Only these widgets seem to be affected.

Clicking edit just brings up today's date and time, and otherwise a white screen.

**Comment by Misplon** [comment]
Hi Yan, strange its only the Button widget. Is it the new button widget? Or the legacy widget? If it's the legacy widget, is Settings > Page Builder > Legacy Bundled Widgets enabled? No need to enable if it's the SiteOrigin Button widget powered by the Widgets Bundle we're discussing.

**Comment by Misplon** [comment]
If it's the new widget, is Plugins > SiteOrigin Widgets > Button widget enabled? If it is, check PHP memory limit, set it to 256m in wp-config.php just to make sure. If that doesn't help, is PHP running ver. 7 or 7.2? If it is, does the issue persist with all other plugins (non-SiteOrigin) disabled?

**Comment by frontenddevguy** [comment]
It's the standard button and call to action widgets.
They were enabled (as they are on live).
I tried disabling and re-enabling them as well as clicking update on the page, logging out and in again.

At first I thought it might be because local needed a theme update but the problem persists after updating and the above steps afterwards

**Comment by Misplon** [comment]
Copy that.

It's a new environment so please try above steps, PHP memory to max in wp-config.php and ensure PHP 7 or 7.2.

**Comment by frontenddevguy** [comment]
PHP is 7.1
http://localhost/phpinfo.php is set to 128M and affects all sites

**Comment by frontenddevguy** [comment]
Nothing changed from localhost and live as they were working fine during development.
Problem persists with PHP 7

**Comment by Misplon** [comment]
That's all the easy points checked off. 

This isn't related to North, it's a Page Builder migration challenge.

There can be migration issues if the data isn't serialized. 
https://deliciousbrains.com/wp-migrate-db-pro/doc/serialized-data/
Looks to be a pro feature of this plugin.

Best to use Duplicator then which covers serialized data in free.

**Comment by frontenddevguy** [comment]
Very strange, I've been using page builder on my last 5 sites, and WP Migrate DB forever and never seen anything like this

**Comment by Misplon** [comment]
Not sure why that's the case but Page Builder does require the data to be migrated with serialized support.

**Comment by frontenddevguy** [comment]
I'm actually using WP Sync DB, which is a free fork of the DB one

**Comment by Misplon** [comment]
So not WP Migrate DB??

**Comment by frontenddevguy** [comment]
owner of WP Sync Db says:

> Yep - so long as you're not doing something weird like storing that data in a flat-file, it'll be migrated because it's just another part of the database. Also, this is literally a copy of wp-migrate-db-pro, so it will do everything that wp-migrate-db-pro will do, except ask you to pay.

**Comment by frontenddevguy** [comment]
Maybe it got corrupted though, I will try pulling across to staging and see what happens.

**Comment by Misplon** [comment]
But after that a user also says:

I dont think so..

Serialized data gets corrupted when replaced with this plugin.

**Comment by Misplon** [comment]
Serialized data not properly handled accounts for 99.99% of our DB migration issues with Page Builder.

Cool, hope this helps you resolve. We do know that Duplicator handles this nicely, so that's our go to in terms of recommending a plugin to do quick and complete site moves. Duplicator gets tricky with bigger files which is where I think they split into Pro if memory serves me, but don't hold me to that. I've been able to move sites with the free version, even larger ones.

**Comment by Misplon** [comment]
And for sure. If this plugin has been working nicely for you in the past, perhaps it was a temporary issue with this particular migration. Definitely worth trying again to see if the problem repeats itself. Hopefully it doesn't :)

Hope the rest of the weekend goes a bit smoother, cheers from Cape Town.

**Comment by frontenddevguy** [comment]
Cool, I will try it.
First time I had a problem with WP Sync DB!
Also tried Wordmove, which is great for files, but couldnt get it to handle the db

**Comment by Misplon** [comment]
Definitely worth another shot. If it's been handling your previous migrations then that would hint at the plugin handling the data correctly.

**Comment by frontenddevguy** [comment]
Thanks for replying so quickly! I will try a few things and update with my findings..

**Comment by Misplon** [comment]
For sure :) Let us know how it goes. Keep Duplicator in mind as an option.

**Comment by frontenddevguy** [comment]
Duplicator does not seem like a usable option with the free version, not supporting replacing existing site content.
I tried pulling across to staging with WP Sync DB, and the issue persists with a slight twist.
The button editor window itself loads, rather than a loading a white screen, but it just continues loading and never retrieves the content.

I did get an alert from Wordfence asking if I wanted to whitelist the url (when clicking on edit button widget), which I have done.
No way I am disabling Wordfence even to test as I run my own Linode and the amount of bad activity is crazy.

One thing I guess may be causing it is that the button widgets contain urls, possibly?

I am about to go on holiday so will park this til I'm back. Definitely not going to mess with the live site until I get local or staging stable.

Thanks again for helping!

**Comment by Misplon** [comment]
I'll ask Alex to comment here on Monday. You can move the DB manually and update the essential data manually, that's an option for sure.

Chat soon. Enjoy the break. Cheers :)

**Comment by AlexGStapleton** [comment]
Based on the initial post, it sounds something is blocking those widgets rather than a general data issue. To clarify, are you able to add a new Button widget and edit it before saving? What about after saving? Have you used this hosting provider before?

Are you using Wordfence locally? While I don't think this is specifically Wordfence blocking it, it is quite possible it's incorrectly flagged us again. Let's check if that's the case, please navigate to **WP Admin > WordFence > Tools** and open **Live Traffic**. Please filter by **Blocked by Firewall** (the text may have recently changed). Do you see your IP in the blocked results? If so, what are some of the results? Do they mention siteorigin or panels_data or anything like that?

**Comment by Misplon** [comment]
Hi Yan :) Please, feel free to reopen this if you want to dive in again based on the feedback from Alex above. Thanks.
