### ISSUE TITLE
Erronneous tags appearing in posts

### ISSUE THREAD

**Issue by frontenddevguy** [siteorigin/siteorigin-north#333]
Searched around for this one and found no hits, so maybe its theme-specific.

I have a client site where new blog posts are showing the wrong tags.
I have checked cache (disabled), cloudflare was switched off and cache purged.

Example:
https://sunskycoaching.co.uk/grow-your-own-superhero-team/

![screen shot 2018-06-26 at 13 06 57](https://user-images.githubusercontent.com/3789940/41910530-d76657b6-7941-11e8-8774-287f500cb566.png)

Here the 'Stephen Hawking' tag is appearing when not set.

It's happening for all new posts, and with other tags also.

**Comment by siteorigin-support** [comment]
Hi Yan

Good to hear from you.

The sidebar contains a Tag Cloud widget which will show all tags, not just tags for the post.

**Comment by frontenddevguy** [comment]
Ah can't believe I missed that! I just need to highlight the active ones.
Thanks :)

**Comment by siteorigin-support** [comment]
-- Please reply above this line --


Hi Siteorigin/siteorigin-North

Thanks for contacting SiteOrigin. 

We’ve received your email and are working on responding as soon as
possible. We’re based in Cape Town, South Africa (GMT+2). Our
business hours are Monday to Friday, 9am to 5pm.

Thanks in advance for your patience and support.
