### ISSUE TITLE
Setting the Medium Text color to #fff will result in inputs being unreadable

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#363]
The Medium Text color setting [applies its styling to inputs](https://github.com/siteorigin/siteorigin-north/blob/1.6.8/inc/settings.php#L580-L583). This is problematic for users who set the Medium Text color to #fff as North doesn't set a custom input background color so in most browsers the text entered into inputs isn't visible due to default input browser styling.

Chrome example:
![](https://i.imgur.com/dBo7gNU.gif)

**Comment by Misplon** [comment]
How often is this being raised? I'm tempted to add a snippet to the docs if it's seldom.

**Comment by AlexGStapleton** [comment]
It's been raised a few times. Honestly, you could get away with a snippet imo
