### ISSUE TITLE
Fix styling of search widget in sidebar.

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-north#37]
Not 100% sure how we should handle this search. Maybe having the search button to the right of the search input. It could also go below the input field.

![screen shot 2016-03-01 at 1 21 31 pm](https://cloud.githubusercontent.com/assets/1126859/13425604/abb3aae2-dfb0-11e5-9b6c-e7b33a07b094.png)

**Comment by Misplon** [comment]
We could remove the Search button / hide it and instead insert a search icon far right. That's quite neat.

**Comment by adiraomj** [comment]
We can just remove the button. Doesn't seem like we will be using it anywhere.

**Comment by adiraomj** [comment]
I like Andrew's suggestion, with sharp corners and a white background it should blend in well with the other fields.

**Comment by adiraomj** [comment]
We also use the design from the psd. It's quite neat too.

![slice 1](https://cloud.githubusercontent.com/assets/3372029/13517774/b91dca76-e1ec-11e5-9ef3-a32112c09e5b.png)

**Comment by gregpriday** [comment]
There we go, that's exactly what we should be using.

**Comment by gregpriday** [comment]
Resolved in https://github.com/siteorigin/siteorigin-north/pull/45
