### ISSUE TITLE
WooCommerce Template Builder: Products Meta widget doesn't output

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#370]
The WooCommerce Template Builder Products Meta widget doesn't output anything when used. The Products Meta widget uses [woocommerce_template_single_meta()](https://docs.woocommerce.com/wc-apidocs/source-function-woocommerce_template_single_meta.html#1518-1523).

**Comment by Misplon** [comment]
Resolved via https://github.com/siteorigin/siteorigin-north/pull/373.
