### ISSUE TITLE
Exclude logo from LiteSpeed Cache lazy loading

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#376]
Exclude the logo from being lazy-loaded by LiteSpeed Cache as we did with JP.

**Comment by Misplon** [comment]
@AlexGStapleton You did the work excluding JP Lazy Loading, please, take a look at this one in the new week. Thanks.

**Comment by AlexGStapleton** [comment]
Figured out how to do this. Where would you like me to put the code for this? template-tags.php?
Also, `siteorigin_north_litespeed_lazy_load_exclude_logo` is a bit long for a function name. Do you have any suggestions for a shorter (but still descriptive) one?

**Comment by AlexGStapleton** [comment]
That feels hard to read and will require a comment to explain things. What about `siteorigin_north_litespeed_lazy_exclude`? It's general but it's clear what is for. It doesn't mention logo, but I think that's fine as it's clearer (and shorter) overall.

**Comment by Misplon** [comment]
That's fine.
