### ISSUE TITLE
Change default form styling

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-north#38]
The default form styling we added might actually need some adjustments. The main issue is that there isn't that much room for the values. For example, the WooCommerce checkout page.

![screen shot 2016-03-01 at 1 24 30 pm](https://cloud.githubusercontent.com/assets/1126859/13425690/2307b3c2-dfb1-11e5-9e7d-659af3566315.png)

Just lowering the side padding should help this.

**Comment by adiraomj** [comment]
Once we place the `Additional Information` is placed below the `Billing Details` ( like in the PSD ), the fields will be less cramped. How about I send a PR with no changes to the side padding and see if it necessary with our new layout?
