### ISSUE TITLE
WooCommerce: Checkout sidebar adjustments

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#430]
Adjust the design of the checkout sidebar to handle a low-value width situation.

![Checkout_-_OLD_LINE_PLATE](https://user-images.githubusercontent.com/789159/210278733-9524a981-6254-4341-ad5c-15d71712ecfc.jpg)

**Comment by AlexGStapleton** [comment]
I'm having trouble replicating the overlap you're getting here. I've tried locally and on the demo site. I can replicate the not-so-great text sizing though. For reference, here's what I see:

![Screenshot 2023-03-08 at 02-44-30 Checkout – SO](https://user-images.githubusercontent.com/17275120/223440883-5a138c62-f657-4326-9ded-ff32d82ea6bd.png)

Are you able to replicate this locally, or on our demo site?

**Comment by Misplon** [comment]
Thanks for checking. I can't replicate at the moment. I'll close until a user reports this again. Cheers.
