### ISSUE TITLE
Check that North WC templates are current

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#431]
siteorigin-north/woocommerce/cart/cart.php version 4.4.0 is out of date. The core version is 7.0.1

siteorigin-north/woocommerce/product-searchform.php version 3.3.0 is out of date. The core version is 7.0.1

siteorigin-north/woocommerce/single-product/add-to-cart/simple.php version 3.4.0 is out of date. The core version is 7.0.1

**Comment by AlexGStapleton** [comment]
This should have been resolved by https://github.com/siteorigin/siteorigin-north/pull/428. I can't seem to trigger this notice with the release version. Can you please confirm whether you're using the latest release or develop?

![Screenshot 2023-01-14 at 04-31-32 WooCommerce status ‹ SO — WordPress](https://user-images.githubusercontent.com/17275120/212357745-61ba2ed2-9377-47c1-ba3a-1f4f44573d53.png)

**Comment by Misplon** [comment]
My bad; looks good.
