### ISSUE TITLE
Add RTL support

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-north#5]
We need to investigate what would all be involved in RTL support and implement it.

[RTL Tester](https://wordpress.org/plugins/rtl-tester/) is a good plugin for testing this.

**Comment by gregpriday** [comment]
We can also look at what Underscores has done to implement RTL.

https://github.com/automattic/_s

**Comment by adiraomj** [comment]
For RTL support we have to add
`body { direction: rtl; unicode-bidi: embed; }`

I was just wondering if we should also flip the layout as well, like so
`.content-area { float: right }`

**Comment by Misplon** [comment]
Anything that has been floated left has to be floated right. Anything that has text align left usually needs text align right. That's the gist of creating a RTL stylesheet.

**Comment by Misplon** [comment]
Brief intro here: https://codex.wordpress.org/Right-to-Left_Language_Support.

Plugin to use in testing: https://wordpress.org/plugins/rtl-tester/

**Comment by adiraomj** [comment]
Should I also apply RTL support for [alignleft](https://github.com/siteorigin/siteorigin-north/blob/develop/style.css#L721) and [alignright](https://github.com/siteorigin/siteorigin-north/blob/develop/style.css#L726).

**Comment by Misplon** [comment]
Good question. Mmm. I think those would stay the same.

**Comment by adiraomj** [comment]
I submitted a PR. It covers rtl support for all the default templates. Please check if everything is working as expected, especially in the main navigation.

I have to complete rtl support for WooCommerce. I will send a PR for it soon.

**Comment by adiraomj** [comment]
For woocommerce RTL support, there is quite a few changes that have to be made. 

One way to go about it to just add the changes to the rtl.css file.

Or we can [disable the default woocommerce stylesheets] (https://docs.woothemes.com/document/disable-the-default-stylesheet/) and make a new woocommerce-rtl.css file that loads for RTL pages.

How would you prefer going about it?

**Comment by gregpriday** [comment]
@adiraomj are you saying that we'd need to override a lot of the core WooCommerce CSS to have full RTL support?

I'd still prefer using a `woocommerce-rtl.css` file that works in conjunction with the core WooCommerce CSS. Mainly because this would be a lot more maintainable than completely replacing it. How difficult would it be to go this route?

**Comment by adiraomj** [comment]
It would definitely be better to maintain. I have started work on this.

I will be making 2 stylesheets, woocommerce-rtl.css and woocommerce-smallscreen-rtl.css. The smallscreen stylesheet will be loaded as it is done in the plugin. 

This will also make it easier for us to disable when the responsive state has been disabled.

**Comment by gregpriday** [comment]
Great, once you've made these changes, update your pull request and I'll check it all out.
