### ISSUE TITLE
Fix mini cart buttons

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-north#56]
It seems like the changes from https://github.com/siteorigin/siteorigin-north/commit/dcb50b2e0a0aa4cdb8cff3c943fa7633d27cb5db also influenced the mini cart buttons. They're both full width now.

<img width="356" alt="screen shot 2016-03-08 at 11 46 57 am" src="https://cloud.githubusercontent.com/assets/1126859/13597884/8e731be8-e523-11e5-9284-768786ecea57.png">

**Comment by adiraomj** [comment]
Sorry about that. I should have checked it before sending the PR. Sent a fix.
