### ISSUE TITLE
Add full accessibility support

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-north#6]
We need to thoroughly implement all the recommended and required [accessibility guidelines](https://make.wordpress.org/themes/handbook/review/accessibility/). Once we've implemented everything, we can add the `accessibility-ready` tag.

**Comment by adiraomj** [comment]
I have started working on this issue. Here is the [branch](https://github.com/adiraomj/siteorigin-north/tree/full-accessibility).

For [Controls](https://make.wordpress.org/themes/handbook/review/accessibility/required/#controls), we will have to convert the search, close and scroll to top icons into links. 

Just  so that I am clear, we will have to enclose them using the `<a>` element and then make changes to the CSS and JS to make them function as they should.

**Comment by gregpriday** [comment]
That sounds good. The method I've seen for this is adding a `text-indent: -9999px;` to this sort of support text to make it hidden.

**Comment by adiraomj** [comment]
Hi. For [Icons](https://make.wordpress.org/themes/handbook/review/accessibility/required/#images) in the post navigation. 

https://github.com/siteorigin/siteorigin-north/blob/develop/inc/template-tags.php#L80

Do we use screen-reader-text or aria-hidden?

**Comment by adiraomj** [comment]
I have sent a PR. Please take a closer look at (and test) the changes I have made WRT 

https://make.wordpress.org/themes/handbook/review/accessibility/required/#controls
https://make.wordpress.org/themes/handbook/review/accessibility/required/#keyboard-navigation 

Everything seemed to be working fine for me.

**Comment by Misplon** [comment]
@adiraomj @gregpriday You guys ready to send this off for the accessibility review? It's a separate review process that we need to enlist the theme in.

**Comment by gregpriday** [comment]
Might be worth it to get that tag. We should probably do our own internal review first though.

**Comment by Misplon** [comment]
Cool, I'll try get that done this week.

**Comment by adiraomj** [comment]
There have been a lot of changes to the theme since this PR. I'll have a look at everything again tomorrow.

**Comment by Misplon** [comment]
Thanks dude, appreciate it.

**Comment by Misplon** [comment]
@adiraomj Apologies for the delay. Will review this week.
