### ISSUE TITLE
Clicks on anchor menu items cause sub-menus to stay open

### ISSUE THREAD

**Issue by gregpriday** [siteorigin/siteorigin-north#60]
On both Chrome and Firefox, when there's a submenu item in the main menu with an anchor link, clicking in it causes the submenu to stay open until the user clicks elsewhere on the screen. The submenu should continue working in the same way after an item is clicked.

<img width="516" alt="screen shot 2016-03-08 at 9 54 30 pm" src="https://cloud.githubusercontent.com/assets/1126859/13614307/870aa010-e578-11e5-8597-be61f8f9f572.png">

So in this case, the `Pricing > A` item has the URL `#`. I clicked on this item, then I was able to hover over another item and view its submenu simultaneously.

**Comment by adiraomj** [comment]
nice catch. Seems like this is a bug in the twentysixteen theme too.
