### ISSUE TITLE
Responsive Menu Issue: Unable to scroll down on device

### ISSUE THREAD

**Issue by AlexGStapleton** [siteorigin/siteorigin-north#63]
When a menu has a lot of items you're unable to scroll the menu down on devices. Please see [this video](http://webm.host/8ab3c/vid.webm) for a visual example of this on an actual device.

**Comment by adiraomj** [comment]
This happens when the sticky menu option has been selected. @gregpriday should we add an option to disable sticky menu for the mobile menu?

**Comment by AlexGStapleton** [comment]
Oh, whoops. Didn't realise it was a sticky menu option. Preventing the user from having a sticky menu on mobile is avoiding the issue imo. A better fix would be to prevent the mobile menu from being sticky when opened.

**Comment by adiraomj** [comment]
@gregpriday I have made the mobile menu dropdown scrollable if it extends beyond the viewport in PR #66 . When functional this adds a scrollbar next the menu, which will probably look fine on mobile devices,  but can look ugly on desktop's. Do you think we need to work on it ( maybe style or remove it)?

**Comment by gregpriday** [comment]
Since the mobile menu is usually going to be displayed on mobile devices, I think having a scrollbar is fine. Don't most mobile browsers hide scrollbars entirely?

**Comment by adiraomj** [comment]
Ya, thats true.

**Comment by AlexGStapleton** [comment]
Has this been patched into the live version? A user is still reporting this is still an issue after the most recent update. I'm going to post the link to his site in the Slack channel for reference.

**Comment by AlexGStapleton** [comment]
Feedback from user who reported this issue initially to me:

1) After the page load, I click on the menu, the menu appear, then I scroll
with my finger : this is the page behind the menu that scroll at first,
after scrolling for a while (I think this is when I reach the top or the
bottom of the page), the menu start to scroll normally.. and it keep
working (scrolling) if you close/reopen the menu.

2) Another issue: when I am in a state where the menu scroll normally, if I
drag by touching a text of the page (barely visible as the menu background
is almost opaque), this is the page that scroll and not the menu.

**Comment by Misplon** [comment]
Thanks @AlexGStapleton. Testing with the latest version we seem to have resolved these issues. If they come up again we can relook at them. In a quick test I did now, the two issues raised don't seem to be occurring.
