### ISSUE TITLE
Main font color isn't changeable in the Customizer

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#67]
Appearance > Customize > Theme Settings > Fonts has a Medium Text Color setting with the default of: #595959. However, this setting doesn't appear to change the main font color in the theme which is set as follows:

```
.page-content,.entry-content,.entry-summary {
    color: #565656;
}
```

**Comment by adiraomj** [comment]
There are quite a few additions that have to be made to css generated with the settings. There are also a lot of places where SCSS variables have not been used.

I will go through everything and send a PR tomorrow.
