### ISSUE TITLE
WooCommerce product quick view

### ISSUE THREAD

**Issue by adiraomj** [siteorigin/siteorigin-north#69]
I have built a basic quick view modal. here is the [branch](https://github.com/adiraomj/siteorigin-north/tree/quick-view)

@gregpriday what do you think about the approach I have taken. Any changes to make?

To do:

- Styling of the quick view layout.
- Modal incoming and outgoing  animation.
- A simple slider to accommodate all product images. (We could use [flickity](http://flickity.metafizzy.co/), its lightweight and feature rich)
- A close button for the modal.
- Loading text/icon till product content is retrieved and displayed.
- Left and Right icons at the edges of the screen to navigate to the next/previous product. (This is something we could explore in future)

**Comment by Misplon** [comment]
@adiraomj Have we made any progress on deciding the scope of this enhancement? Thanks :)

**Comment by adiraomj** [comment]
@Misplon in the customizer under `WooCommerce` there is an option to activate Quickview. This adds a button to the product archives. Please do check out it's functionality and design. If need be, we can make enhancements/chenges. Let me know. :)

**Comment by Misplon** [comment]
@adiraomj Looks great. Do you think we should add a close icon for the modal? I know it closes when clicking outside of it, just wondering if we should also add a close icon for usability.

**Comment by adiraomj** [comment]
Sure thing. I'll send a PR tomorrow. :)

**Comment by adiraomj** [comment]
Where do you think we should place the close icon? Top right of the modal or top right of the window?

**Comment by Misplon** [comment]
@adiraomj I was thinking top right of the modal.

**Comment by Misplon** [comment]
@adiraomj Let me know once you've had a chance to take a look at this final addition. Thanks dude :)

**Comment by adiraomj** [comment]
@Misplon I have added a close icon. Please have a look at it. Let me know if I should make any css changes.
