### ISSUE TITLE
Add current menu item indication

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#77]
Consider adding an indicator or just keep the hover state for the current menu item.

**Comment by Misplon** [comment]
Perhaps something like:

```
.main-navigation .current_page_item > a,
.main-navigation .current-menu-item > a,
.main-navigation .current_page_ancestor > a {
	color: #c75d5d;
}
```

**Comment by adiraomj** [comment]
Do you think we need to add an option in the settings for this feature?

**Comment by Misplon** [comment]
The settings are quite lightweight at the moment so I'm not sure it would fit in with that approach to have a setting for this. @gregpriday what you reckon?

**Comment by Misplon** [comment]
@adiraomj Sorry for the late reply on this. Is the current menu color linked to any of the Customizer color settings? I took a quick look around now and it doesn't look like it.

**Comment by adiraomj** [comment]
It is linked to the `Text Dark Color`. I had forgotten to update the settings CSS. Sorry about that. I have sent a PR to sort it out.

**Comment by Misplon** [comment]
Super, thanks for sorting that out.
