### ISSUE TITLE
Mobile menu isn't scrollable on desktop

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#81]
If the mobile menu is longer than the screen it isn't scrollable. The user define breakpoint means that some users might want to push the mobile menu to desktop resolutions.

**Comment by adiraomj** [comment]
I think this is the same issue as #63 . It has been addressed with #66. The fix should be available in the next version that @gregpriday rolls out. :-)

**Comment by SimoneGoudzwaard** [comment]
The submenu is not scrollable in the **pc-mode**. When having a long list, the sub-menu is cut-off.

**Comment by Misplon** [comment]
Solved in https://github.com/siteorigin/siteorigin-north/pull/66
