### ISSUE TITLE
Mobile menu: add Customizer settings to change it's colors.

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#84]
Consider adding color settings for the mobile menu so that users can customize it. Not exactly sure where these should go. @gregpriday.

**Comment by Misplon** [comment]
@adiraomj I think we should provide three settings, one for the background and one for the color of the text and one for the background color opacity., that would make the responsive menu fully customizable in terms of color. I haven't had a chance to check out our new Customizer settings framework yet. Do we have anything handy in there for opacity? @gregpriday

**Comment by Misplon** [comment]
Do you guys think it would be most logical for these settings to go in the Responsive section?

**Comment by adiraomj** [comment]
Yup, adding these to the Responsive section does seem most appropriate.

**Comment by Misplon** [comment]
Sweet, thanks.

**Comment by adiraomj** [comment]
I am implementing this issue in the [branch](https://github.com/adiraomj/siteorigin-north/tree/mobileMenuColors) and have run into a little problem.

I have used SASS variables to generate the background colors like so: https://github.com/adiraomj/siteorigin-north/blob/mobileMenuColors/sass/navigation/_menus.scss#L327

When I try to generate the settings css using `./create_css.php`, I run into the following error:
```
Error: $color: "${responsive_mobile_menu_background_color}" is not a color for `rgba'
        on line 327 of /private/var/folders/3s/6ts826px2fz6rnbvlsx8frpr0000gn/T/rNCIcg/sass/navigation/_menus.scss
        from line 9 of /private/var/folders/3s/6ts826px2fz6rnbvlsx8frpr0000gn/T/rNCIcg/sass/navigation/_navigation.scss
        from line 72 of /private/var/folders/3s/6ts826px2fz6rnbvlsx8frpr0000gn/T/rNCIcg/sass/style.scss
  Use --trace for backtrace.
```

Any ideas on solving this? @Misplon @gregpriday . Thanks

**Comment by gregpriday** [comment]
Yeah, that's a bit of a limitation with that CSS generator script. Colors can't be passed through rgba functions. If you can't get away without this, then I'll try improve the script to handle this. It'll take a little bit of work - but it's probably a worthwhile enhancement.

**Comment by adiraomj** [comment]
It will definitely be worth it. I'm sure we will run into this issue in other themes. :)

**Comment by Misplon** [comment]
@adiraomj Quick update: chatting to @gregpriday about this. We at least need a Hex2RGB function in the settings framework but ideally, something to handle RGBA so we can let users set opacity for certain backgrounds. Hopefully, this is something Greg can release soon. Let's briefly pause this until that functionality is ready. Thanks :)

**Comment by gregpriday** [comment]
Working on this now.

**Comment by gregpriday** [comment]
@adiraomj just pushed a couple updates to the Settings framework, so it handles the RGBA function properly now. It might be a bit finicky, but I've tested it with your branch and it's working there.

https://github.com/siteorigin/settings/commit/708c3a2068c4c525b053786024d064f3d32236a7
https://github.com/siteorigin/settings/commit/ef52b64d7b943efc54ae91161951e071c48de1c7

**Comment by Misplon** [comment]
👍

**Comment by gregpriday** [comment]
I also added support for the core WordPress range customizer field in https://github.com/siteorigin/settings/commit/8ff67c16e1497986b044a456355d956cda1bde0c and https://github.com/siteorigin/settings/commit/52d39481553b2e2ad26adabc3a701732b2a71302

It's fairly easy to support:

```
'mobile_menu_background_opacity' => array(
	'type'        => 'range',
	'label'       => __( 'Mobile Menu Background Opacity', 'siteorigin-north' ),
	'description' => __('0 is transparent and 1 is opaque', 'siteorigin-north'),
	'min'         => 0,
	'max'         => 1,
	'step'        => 0.01,
	'live'        => true,
),
```

Although the description isn't as important with a range. Most users will be able to figure that out.

**Comment by adiraomj** [comment]
Nice stuff 👍   I'll check them out now..
