### ISSUE TITLE
Mobile menu: add a toggle for sub-menu items

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#85]
Sub-menu items are displayed in the mobile menu. Let's consider hiding them and adding a down arrow on the far right of the parent menu item. If the down arrow is clicked/tapped, the sub-menu will be exposed and the arrow will change to an up arrow. The same will happen for any nested sub-menu items.

**Comment by adiraomj** [comment]
This is what we have used for [Unwind's](https://github.com/siteorigin/siteorigin-unwind) mobile dropdown  menu.

I do not think this was envisioned for North's mobile menu. What do you think @gregpriday?

**Comment by Misplon** [comment]
Sure, I hear you that it wasn't envisaged. The challenge users face with auto displayed drop downs is that if they have a big menu with a lot of sub-menus, their responsive menu will be massive. I think users would benefit by toggled sub-menus in North. I'm sure we can make it fit with the design.

**Comment by Misplon** [comment]
@adiraomj I had a quick phone meeting with @gregpriday now, he's happy to proceed with this. Let's make say 80% of the parent `ul` item click through to the link and then say 20% of the space on the right dedicated to clicking the arrow to initiate the sub-menu view.

Greg would like us to introduce a setting for this option but make it default ON. Thanks man.

**Comment by adiraomj** [comment]
Cool. Will get started on this @Misplon 👍

**Comment by Misplon** [comment]
Awesome! Thanks :)
