### ISSUE TITLE
Main menu drop-downs don't work for touch users

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#89]
If the mobile menu collapse value is low, 480 for example, phone landscape and tablet users will be presented with the main menu. Drop-down menu items aren't accessible because on the first tap, parent menu items are going straight to their link instead of first showing their drop down-menu.

**Comment by SimoneGoudzwaard** [comment]
What is the status on this one?

**Comment by Misplon** [comment]
Hi Simone
The status is listed in the top left corner, it's currently still open. As soon as it's been attended to this ticket will be updated. This issue does have priority and will be attended to as soon as possible.

**Comment by SimoneGoudzwaard** [comment]
Thanks for the reply Andrew. Can you give an indication on how much longer it will take? I really need to put my site life and don't want to use the mobile menu on a tablet (a. the scroll isn't stable on a tablet, b. I find the submenu really ugly on a tablet).

**Comment by Misplon** [comment]
Thanks for your support and understanding. We'll have an update ready for you by the end of the week. It will most likely be sooner but I'd rather not promise that and miss the deadline. As soon as it's ready we'll send you a pre-release version of the theme as we did before.

**Comment by SimoneGoudzwaard** [comment]
I will not hold you to it. I know how busy you all are, even more busy with me constantly nagging. Be prepared for big hugs and kissed when this is solved. Than you can forward them to Greg. :-)

**Comment by Misplon** [comment]
I'll have a chance to test a few of the recent commits this afternoon. Once I've run through the list and checked the additions and fixes I'll update you on our thread here: https://siteorigin.com/thread/one-pager-trouble/. Once I've done that I should be able to provide a more accurate time for building a pre-release for you :)

**Comment by SimoneGoudzwaard** [comment]
Super!!!!!

**Comment by Misplon** [comment]
No problem at all. Thanks for all of your efforts in improving North, we really appreciate your efforts and detailed feedback.
