### ISSUE TITLE
jQuery Smooth Scroll flashes before scrolling

### ISSUE THREAD

**Issue by Misplon** [siteorigin/siteorigin-north#99]
When clicking an anchor link there is a brief flash as the link is clicked. Can we look at stopping this happening?

http://stackoverflow.com/questions/12975577/why-does-smooth-scroll-flash-before-scrolling

**Comment by adiraomj** [comment]
@Misplon `e. preventDefault ();` is being used in our code.

@gregpriday is this [line of code](https://github.com/siteorigin/siteorigin-north/blob/develop/js/north.js#L371) necessary?  Seems to be causing the problem.

**Comment by gregpriday** [comment]
It might not be necessary if we also remove that preventDefault call. If
you remove those lines and it still works, then all good. There shouldn't
be any knock on effects.
